import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  weekendText: {
    color: '#FF0000',
  },
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 90,
  },
  header: {
    paddingTop: 54,
    paddingBottom: 16,
    backgroundColor: '#4F8EF7',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  navIconContainerRight: {
    padding: 4,
  },
  todayButtonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 4,
  },
  todayButtonHeaderText: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  headerText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  calendar: {
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
  },
  calendarContainer: {
    margin: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  todayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 16,
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  todayButtonText: {
    color: '#4F8EF7',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  dayContainer: {
    width: 40,
    height: 54,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 3,
    borderRadius: 8,
    marginVertical: 1,
  },
  selectedDay: {
    backgroundColor: '#E3EDFC',
  },
  dayText: {
    fontSize: 16,
    color: '#222',
    fontWeight: '500',
  },
  dayTextSelected: {
    color: '#4F8EF7',
    fontWeight: 'bold',
  },
  todayText: {
    borderBottomWidth: 2,
    borderBottomColor: '#4F8EF7',
  },
  dayDisabled: {
    color: '#ccc',
  },
  eventPreviewWrap: {
    marginTop: 2,
    alignItems: 'center',
  },
  eventPreviewText: {
    fontSize: 10,
    color: '#4F8EF7',
    maxWidth: 34,
  },
  eventPreviewMore: {
    fontSize: 9,
    color: '#aaa',
    marginTop: -2,
  },
  eventSection: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    marginTop: 18,
    padding: 16,
    elevation: 2,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#4F8EF7',
  },
  noEvent: {
    color: '#888',
    textAlign: 'center',
    marginTop: 16,
  },
  eventItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingVertical: 8,
    paddingRight: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    position: 'relative',
  },
  deleteButton: {
    position: 'absolute',
    right: 0,
    padding: 8,
  },
  eventTime: {
    color: '#4F8EF7',
    fontWeight: 'bold',
    width: 60,
  },
  eventText: {
    fontSize: 16,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 36,
    backgroundColor: '#4F8EF7',
    borderRadius: 28,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
});

export default styles;
