import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const PRIMARY_COLOR = '#4F8EF7';
const SECONDARY_COLOR = '#F5F5F5';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 50,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginBottom: 30,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 20,
  },
  input: {
    backgroundColor: SECONDARY_COLOR,
    paddingHorizontal: 15,
    paddingVertical: Platform.OS === 'ios' ? 15 : 12,
    borderRadius: 10,
    fontSize: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  // 🆕 추가된 스타일: 비활성화된 입력 필드
  disabledInput: {
    backgroundColor: '#F5F5F5',
    color: '#999999',
  },
  loginButton: {
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  loginButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  // 🆕 추가된 스타일: 비활성화된 버튼
  disabledButton: {
    opacity: 0.6,
  },
  // 🆕 추가된 스타일: 비활성화된 텍스트
  disabledText: {
    color: '#CCCCCC',
  },
  oauthContainer: {
    width: '100%',
    marginBottom: 20,
    gap: 12,
    flexDirection: 'column',
  },
  kakaoButton: {
    backgroundColor: '#FEE500',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 15,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  naverButton: {
    backgroundColor: '#03C75A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 15,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  appleButton: {
    backgroundColor: '#000000',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 15,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  oauthIconContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  naverLogoText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  kakaoButtonText: {
    color: 'rgba(0, 0, 0, 0.85)',
    fontSize: 16,
    fontWeight: 'bold',
  },
  naverButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  appleButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  wavveLoginButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    width: '100%',
    height: 50,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  wavveButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  wavveLogoContainer: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  wavveLogo: {
    width: 30,
    height: 30,
  },
  wavveButtonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  googleLoginButton: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#747775',
    borderRadius: 4,
    height: 44,
    paddingHorizontal: 16,
    justifyContent: 'center',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
  },
  googleButtonContentWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
  },
  googleButtonIcon: {
    marginRight: 12,
    width: 20,
    height: 20,
  },
  googleLoginText: {
    color: '#1f1f1f',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.25,
  },
  kakaoLoginButton: {
    backgroundColor: '#FEE500',
    borderRadius: 15,
    width: '100%',
    height: 50,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  kakaoButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  kakaoLogo: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  appleLoginButton: {
    backgroundColor: '#000000',
    borderRadius: 15,
    width: '100%',
    height: 50,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  appleButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  appleIcon: {
    marginRight: 8,
  },
  signupContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signupText: {
    color: '#888',
    marginRight: 5,
  },
  signupLink: {
    color: PRIMARY_COLOR,
    fontWeight: 'bold',
  },
  socialLoginContainer: {
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
  },
  socialLoginText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 15,
  },
  loginBtn: {
    width: '100%',
    height: 50,
    backgroundColor: '#007bff',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    elevation: 3,
  },
  signupBtn: {
    width: '100%',
    height: 50,
    backgroundColor: '#6c757d',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    elevation: 3,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  kakaoBtn: {
    width: 240,
    height: 50,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#FEE500',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kakaoImg: {
    width: 240,
    height: 50,
  },
  kakaoButton: {
    width: '100%',
    height: '100%',
    backgroundColor: '#FFE812',
    borderRadius: 10,
    padding: 5,
  }
});

